"""Cross-check the Python feature extraction in train.py against the frozen
JS vectors in model/parity.json (generated by `npm run gen:parity`).

Run after any change to feature semantics:
    python model/check_parity.py

JS vectors pass through Float32Array, so compare after a float32 cast
(e.g. entropy 3.0391 freezes as 3.039099931716919), not decimal-exact.
"""
import json
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from train import features, FEATURE_NAMES  # noqa: E402

cases = json.loads((pathlib.Path(__file__).parent / 'parity.json').read_text())
failures = 0
for c in cases:
    py = np.array(features(c['url']), dtype=np.float32)
    js = np.array(c['vector'], dtype=np.float32)
    if not np.allclose(py, js, atol=1e-6):
        failures += 1
        print(f"MISMATCH {c['url']}")
        for name, a, b in zip(FEATURE_NAMES, py, js):
            if not np.isclose(a, b, atol=1e-6):
                print(f"  {name}: py={a} js={b}")
if failures:
    print(f"{failures}/{len(cases)} parity cases FAILED")
    sys.exit(1)
print(f"All {len(cases)} parity cases match (JS <-> Python).")
